### PR TITLE
Fix snapshot showing the UI

### PR DESCRIPTION
**Pull request by sercero**

### CODE REVIEW

**Comment by paroj** [comment]
which rendersystem are you using? works here for me

**Comment by sercero** [comment]
OpenGL 3+, you'll see that my latest screenshots were partially showing the UI.

**Comment by paroj** [comment]
it seems that our imgui code lags behind by one frame. I would like to investigate this first, before adding this workaround

**Comment by paroj** [comment]
imgui does not seem to lag. please try again, whether latest master fixes the issue

**Comment by sercero** [comment]
> imgui does not seem to lag. please try again, whether latest master fixes the issue

OK, it'll take me a while because I never built OGRE with python support.

Lets see how it goes...

**Comment by paroj** [comment]
> OK, it'll take me a while because I never built OGRE with python support.

oh, I meant meshviewer master. The changes are on python side.

Also, for ogre the master SDK includes the python bindings:
https://dl.cloudsmith.io/public/ogrecave/ogre/raw/versions/master/ogre-sdk-master-msvc142-x64.zip

**Comment by sercero** [comment]
> > OK, it'll take me a while because I never built OGRE with python support.
> 
> oh, I meant meshviewer master. The changes are on python side.
> 
> Also, for ogre the master SDK includes the python bindings: https://dl.cloudsmith.io/public/ogrecave/ogre/raw/versions/master/ogre-sdk-master-msvc142-x64.zip

Oh, thanks.

Yes, I saw in `create_win_package.bat` that you download that package but since it was "master"....

No problem now I understand.

**Comment by sercero** [comment]
Yes, now it works.

Thanks.

**Comment by paroj** [comment]
FYI the issue was that we were downloading the image from the backbuffer after swap buffers. This is platform specific and can result in an image that is 2 frames old.

**Pull request closed without merging**
